services:
  # Go version (default)
  stobot-go:
    image: stobot:latest
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep stobot || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file: 
      - .env